import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientWrapper from './components/ClientWrapper';
import Header from "./components/Header";
import { ThemeProvider } from './components/theme-provider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Agent Tube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html  lang="en"> 
  <head>
    <meta />
  </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
        
        <ClientWrapper>
         <Header />
          {children}
        </ClientWrapper>
        </ThemeProvider>
      </body>
    </html>
    
  );
}
